framework:
    default_locale: en
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
        providers:
            loco:
                dsn: '%env(LOCO_DSN)%'
                domains: ['messages']
                locales: ['en', 'fr']
        pseudo_localization:
         accents: true
         expansion_factor: 1.4
         parse_html: true
         localizable_html_attributes: ['title']


